#%RAML 1.0
title: offerAPI
version: 1.0
baseUri: /api/retail/application

types:
  offer:
    properties: 
      id: string
      desc: string
      type: string
      creditLimit: number
      interestRate: number
      incentives: special[]
      startDate: datetime
      endDate: datetime
      target: group[]
  
  offers:
    properties: 
      result: [group]

  special:
    properties:
      id: string
      desc: string
  
  specials:
    properties: 
      result: [special]
  
  group:
    properties: 
      id: string
      desc: string
      groupId: string
      range: string

  groups:
    properties: 
      result: [group]

/:
  post:
    body: 
      application/json:
        type: offer
        properties: 
          desc: string
          type: string
          creditLimit: number
          interestRate: number
          incentives: special[]
          startDate: datetime
          endDate: datetime
          target: group[]
    responses: 
      200:
        body: 
          application/json:
            example:
              {
                "message": "ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1"
              }
  get:
    responses: 
      200:
        body: 
          application/json:
            type: offers          
/{id}:
  uriParameters: 
    id: string
  get:
    responses: 
      200:
        body:
          application/json:
            type: offer
            example: 
              {
                "id": id,
                "desc": "Interest Free till next year",
                "type": "creditcard",
                "creditLimit": 500,
                "interestRate": 20,
                "incentives": [],
                "startDate": "2018-02-28T16:41:41.090Z",
                "endDate": "2018-08-28T16:41:41.090Z",
                "target": []
              }
            
  put:
    body: 
      application/json:
        type: offer
    responses: 
      204:
        body: 
          application/json:
            example:
              {
                "message": "Update completed"
              }
      400:
        body:
          application/json:
            example:
              {
                "message": "Could not resolve mapping"
              }
      404:
        body: 
          application/json:
            example:
              {
                "message": "User not found"
              }
  delete:
    body: 
      application/json:
        type: offer
    responses: 
      400:
        body:
          application/json:
            example:
              {
                "message": "Could not resolve mapping"
              }
      404:
        body: 
          application/json:
            example:
              {
                "message": "User not found"
              }
/special:
  post:
    body:
      application/json:
        type: special
  get:
    responses: 
      200:
        body: 
          application/json:
            type: specials
  /{id}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: special
    put:
      body: 
        application/json:
          type: special
    delete:
      body: 
        application/json:
          type: special

/group:
  post:
    body:
      application/json:
        type: group
  get:
    responses: 
      200:
        body:
          application/json:
            type: groups
        
  /{id}:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: group
        404:
          body: 
            application/json:
              example:
                {
                  "message": "user not found"
                }
    put:
      body:
        application/json:
          type: group
      responses:
        204:
          body: 
            application/json:
              example: {
                "message": "group updated"
              }
        404:
          body: 
            application/json:
              example:
                {
                  "message": "user not found"
                }
        400:
          body:
            application/json:
              example:
                {
                  "message": "mapping failed"
                }
    delete:
      body:
        application/json:
          type: group
      responses:
        204:
          body: 
            application/json:
              example: {
                "message": "group updated"
              }
        404:
          body: 
            application/json:
              example:
                {
                  "message": "user not found"
                }
        400:
          body:
            application/json:
              example:
                {
                  "message": "mapping failed"
                }