#%RAML 1.0
version: v2
title: Credit Score API
description: Will display the credit score of a user based on their banking activity
baseUri: ''
types:
  Credit-Score-Output:
    type: object
    properties:
      customer-id:
        required: true
        format: int32
        example: 1
        type: integer
      credit-score:
        required: true
        maximum: 90
        minimum: 15
        format: int32
        example: 56
        default: 45
        type: integer
  Credit-Card-Info:
    description: Information on all credit cards
    type: object
    properties:
      total-cards:
        required: true
        minimum: 0
        format: int32
        example: 3
        type: integer
      total-balance:
        required: true
        minimum: 0
        format: float
        example: 12000
        type: number
      payments:
        required: true
        type: Payments-Made
  Payments-Made:
    type: object
    properties:
      total:
        required: true
        minimum: 0
        format: int32
        example: 12
        description: Total payments made
        type: integer
      total-late:
        required: true
        minimum: 0
        format: int32
        example: 3
        description: Late payment
        type: integer
  Loan-Info:
    description: Information on all loans
    type: object
    properties:
      total-loans:
        required: true
        minimum: 0
        format: int32
        example: 1
        type: integer
      total-principle:
        required: true
        minimum: 1
        format: float
        example: 23000
        description: The original loan amount
        type: number
      total-balance:
        required: true
        minimum: 0
        format: float
        example: 21.87
        type: number
      payments:
        required: true
        type: Payments-Made
  Occupation-Info:
    type: object
    properties:
      job-term:
        required: true
        example: part-time
        type: string
      annual-income:
        required: true
        minimum: 0
        format: float
        example: 87000
        type: number
/getcreditscore:
  get:
    responses:
      '200':
        description: Will return the most recent credit score of the customer
        body:
          application/json:
            type: Credit-Score-Output
    queryParameters:
      customer-id:
        minimum: 1
        format: int32
        example: 12
        description: The customer id of who the credit score belongs to
        type: integer
  post:
    responses:
      '200':
        body:
          application/json:
            description: 'Will create an updated credit score '
            type: Credit-Score-Output
    body:
      application/json:
        type: object
        properties:
          user:
            required: true
            type: object
            properties:
              customer-id:
                required: true
                minimum: 0
                format: int32
                example: 13
                type: integer
              age:
                required: true
                example: 12
                type: integer
              occupation:
                required: true
                type: Occupation-Info
              
          account-history:
            required: false
            type: object
            properties:
              credit-cards:
                required: false
                type: Credit-Card-Info
              loans:
                required: false
                type: Loan-Info
