#%RAML 1.0
title: NDF - Managers API
version: v1
baseUri: https://api.ndf-managers.com
/manager:
  /Aprove:
    /{id}:
      post:
	queryParameters:
	  description: Approve the loan with loanid = {id}
	  access_token:
	    displayName: Access Token
	    type: string
            description: Token giving permision to make call
	    required: True
	responses:
          200:
	    body:
	      application/json:
		example:  |
		  {"message": "Loan approved"}
	  404:
	    body:
	      application/json:
		example:  |
		  {"message": "Loan not found"}
  /Deny:
    /{id}:
      post:
	queryParameters:
	  description: Deny the loan with loanid = {id}
	  access_token:
	    displayName: Access Token
	    type: string
            description: Token giving permision to make call
	    required: True
	responses:
          200:
	    body:
	      application/json:
		example:  |
		  {"message": "Loan denied"}
	  404:
	    body:
	      application/json:
		example:  |
		  {"message": "Loan not found"}