#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/56b99a12-d3cc-4f01-a1b1-392a5521fb25 # 
title: DTIR
version: v1
description: This API recieves the salary, debt, and duration for a loan and returns debt to income ratio
types:
  DTRI-MODEL:
    type: object
    properties:
      loan-amount:
        required: true
        type: number
        example: 200000
        minimum: 1
/dtir:
  post:
    responses:
      '200':
        body:
          application/json:
            description: calculates the loan amount based on salary, debt, and duration.
            type: DTRI-MODEL
    body:
      application/json:
        type: object
        properties: 
          applicant-info:
            required: true
            type: object
            properties:
              salary:
                required: true
                type: number
                minimum: 0
              debt:
                required: true
                type: number
                minimum: 1
        
            