#%RAML 1.0
---
title: payment API
baseUri: http://localhost/operations
version: v1

/payment:
  get:
    responses:
      200:
        body: 
          application/json:
            example: |
              {
               "data": {
                  "transactionalID": "1",
                  "date": "2018-10-15",
                  "amount": "100.26",
                  "cardnumber": "1111 2222 3333 4444",
                  "source": "Amazon",
                  "description": "A payment of $100.26 to credit card 1111 2222 3333 4444",
                  "status": "approved",
                  "Type": "payment"
                }
              }
      404:
        body:
          application/json:
            example: |
              {"message": "Transactions could not be retrieved"}
  post:
    body:
      application/json:
        type: object
        properties: 
          date:
            displayName: date
            type: date-only
            description: The date that the payment took place
            example: 2018-10-15
            required: true
          amount:
            displayName: amount
            type: number
            description: The amount of money that was payed
            example: 100.26
            required: true
          cardnumber:
            displayName: cardNumber
            type: string
            description: Foreign key to the Credit Card table
            example: 1111 2222 3333 4444
            required: true
          source:
            displayName: source
            type: string
            description: The source of the payment
            example: Amazon
            required: true
          description:
            displayName: description
            type: string
            description: A description of the payment
            example: A payment of $100.26 to credit card 1111 2222 3333 4444
            required: true
          status:
            displayName: status
            type: string
            description: Whether or not the transaction is pending approval
            example: approved
            required: true
          Type:
            displayName: type
            type: string
            description: What type of transaction took place
            example: payment
            required: true
    responses:
      200:
        body: 
          application/json:
            example: |
              {
               "data": {
                  "transactionalID": "1",
                  "date": "2018-10-15",
                  "amount": "100.26",
                  "cardnumber": "1111 2222 3333 4444",
                  "source": "Amazon",
                  "description": "A payment of $100.26 to credit card 1111 2222 3333 4444",
                  "status": "approved",
                  "type": "payment"
                }
              }
      404:
        body:
          application/json:
            example: |
              {"message": "Transactions could not be retrieved"}
  /accountid:
      post:
        body:
          application/json:
            type: object
            properties:
              accountid:
                displayName: accountID
                type: string
                description: Foreign key to the Credit Card and loan table
                example: 1111 2222 3333 4444
                required: true
        responses:
          200:
            body: 
              application/json:
                example: |
                  {
                   "data": {
                      "transactionalID": "1",
                      "date": "2018-10-15",
                      "amount": "100.26",
                      "cardnumber": "1111 2222 3333 4444",
                      "source": "Amazon",
                      "description": "A payment of $100.26 to credit card 1111 2222 3333 4444",
                      "status": "approved",
                      "type": "payment"
                    }
                  }
          404:
            body:
              application/json:
                example: |
                  {"message": "Transactions could not be retrieved"}