#%RAML 1.0
version: v2
title: RiskInputAPI
description: Input API for Risk management
baseUri: https://mocksvc.mulesoft.com/mocks/7920ec47-5548-4cbe-859e-b83475349121 # baseUri: ''

types:
  customer:
    type: object
    properties: 
      customer-id:
        required: true
        format: int32
        example: 1
        type: integer
      customer-name:
        required: true
        maxLength: 50
        type: string
      customer-dob:
        required: true
        type: date-only
      customer-occupation:
        required: true
        type: occupation
      customer-payment-history:
        required: true
        type: account-history

  occupation:
    type: object
    properties:
      occupation-term:
        required: true
        example: part-time
        type: string
      occupation-income:
        required: true
        minimum: 0
        format: float
        example: 87000
        type: number

  account-history:
    type: object
    properties: 
      credit-cards:
        type: credit-card[]
      loans:
        type: loan[]


  credit-card:
    type: object
    properties:
      cc-number:
        default: 0
        format: int32
        type: integer
      holder-name:
        required: true
        maxLength: 50
        type: string
      cc-limit:
        default: 0
        format: float
        type: number
      cc-balance:
        default: 0
        format: float
        type: number
      exp-date:
        required: true
        type: date-only
      
  loan:
    type: object
    properties: 
      principle:
        default: 0
        format: float
        type: number
      balance:
        default: 0
        format: float
        type: number
      
  payment:
    type: object
    properties: 
      late:
        default: false
        type: boolean

/customers:
  get:
    responses: 
      200:
        description: returns all the customers and their information
        body:
          application/json:
            type: customer[]

  post:
    responses: 
      200:
        description: posts information to a customer
        body: 
          application/json:
            type: customer
            
  /{customer-id}:
    get:
      responses: 
        200:
          description: returns a customer with all of the customer's information
          body:
            application/json:
              type: customer
    /credit-cards:
      get:
        responses:
          200:
            description: returns all the credit cards of a particular customer
            body:
              application/json:
                type: credit-card[]
      post:
        responses: 
          200:
            description: creates a credit card for a customer
            body:
              application/json:
                type: credit-card
      
    /loans:
      get:
        responses: 
          200:
            description: returns all the loans of a particular customer
            body:
              application/json:
                type: loan[]
      post:
        responses: 
          200:
            description: creates a loan for a customer
            body: 
              application/json:
                type: loan
    