#%RAML 1.0
version: v1
baseUri: https://mocksvc.mulesoft.com/mocks/d0104357-ff73-4b58-81d1-7ec998cba00a # 
title: riskrec
description: Gives an accurate number on a scale of 1 to 5 (1  being no risk, 5 being far too much risk)
types: 
  Risk-Level-Output:
    type: object
    properties: 
      risk-level:
        required: true
        type: integer
        example: 1
        maximum: 5
        minimum: 1
/risk:
  post:
    responses: 
      '200':
        body: 
          application/json:
            description: Responds with a single number representing the risk level of the loan
            type: Risk-Level-Output
    body: 
      application/json:
        type: object
        properties: 
          borrower:
            required: true
            type: object
            properties: 
              credit-score:
                required: true
                type: integer
                minimum: 15
                maximum: 90
              loan-amt:
                required: true
                type: integer
                minimum: 1
              loan-dur:
                required: true
                type: integer
                minimum: 1
              curr-income:
                required: true
                type: integer