#%RAML 1.0
title: offerAPI
version: 1.0
baseUri: /api/retail/application

types:
  appForm:
    properties:
      active: boolean
      id: string
      offer: string
      sentIn: datetime
      started: datetime
      status: string
      userId: string

  offer:
    properties: 
      id: string
      desc: string
      type: string
      creditLimit: number
      interestRate: number
      incentives: string[]
      startDate: datetime
      endDate: datetime
      target: string[]
      active: boolean
  
  offers:
    properties: 
      result: [group]

  special:
    properties:
      id: string
      desc: string
      active: boolean
  
  specials:
    properties: 
      result: [special]
  
  group:
    properties: 
      id: string
      name: string
      desc: string
      userId: string[]
      active: boolean

  groups:
    properties: 
      result: [group]

/:
  post:
    body: 
      application/json:
        type: appForm
    responses: 
      200:
        body: 
          application/json:
            example: {"ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1"}

  /{id}:
    uriParameters: 
      id: string
    get:
      responses: 
        200:
          body:
            application/json:
              type: appForm
              example: 
                {
                  "active":true,
                  "id": "ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1",
                  "offer":"ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1",
                  "sentIn": "2018-02-28T16:41:41.090Z",
                  "started": "2018-02-28T16:41:41.090Z",
                  "status": "submitted",
                  "userId": "ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1"
                }
            
    put:
      body: 
        application/json:
          type: appForm
      responses: 
        204:
          body: 
            application/json:
              example: {"Update completed"}
        400:
          body:
            application/json:
              example: {"Could not resolve mapping"}
        404:
          body: 
            application/json:
              example: {"User not found"}
    delete:
      body: 
        application/json:
          type: appForm
      responses: 
        400:
          body:
            application/json:
              example: {"Could not resolve mapping"}
        404:
          body: 
            application/json:
              example: {"User not found"}
/special:
  post:
    body:
      application/json:
        type: special
    responses:
      204:
        body:
          application/json:
            example: {"ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1"}
      404:
        body:
          application/json:
            example: {"ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1 not found"}
  get:
    responses: 
      200:
        body: 
          application/json:
            type: specials
  /{id}:
    uriParameters:
      id: string
    get:
      responses: 
        200:
          body: 
            application/json:
              type: special
    put:
      body: 
        application/json:
          type: special
      responses:
        204:
          body:
            application/json:
              example: {"ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1 updated"}
        404:
          body:
            application/json:
              example: {"ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1 not found"}
          
    delete:
      body: 
        application/json:
          type: special
      responses:
        202:
          body:
            application/json:
              example: {"ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1 marked for deletion"}
        404:
          body:
            application/json:
              example: {"ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1 not found"}

/group:
  post:
    body:
      application/json:
        type: group
  get:
    responses: 
      200:
        body:
          application/json:
            type: groups
        
  /{id}:
    uriParameters:
      id: string
    get:
      responses: 
        200:
          body: 
            application/json:
              type: group
        404:
          body: 
            application/json:
              example: {"user not found"}
    put:
      body:
        application/json:
          type: group
      responses:
        204:
          body: 
            application/json:
              example: {"group updated"}
        404:
          body: 
            application/json:
              example: {"user not found"}
        400:
          body:
            application/json:
              example: {"mapping failed"}
    delete:
      body:
        application/json:
          type: group
      responses:
        204:
          body: 
            application/json:
              example: {"group updated"}
        404:
          body: 
            application/json:
              example: {"user not found"}
        400:
          body:
            application/json:
              example: {"mapping failed"}

/offer:
  post:
    body:
      application/json:
        type: offers
    responses:
      200:
        body:
          application/json:
            example: {"ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1"}
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "active": true,
                "id": "ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1",
                "offer": "ef3a5a5c-e441-11e8-9f32-f2801f1b9fd1",
                "sentIn": "",
                "started": "",
                "status": "submitted",
                "userId": ["tf3a5a5c-e441-11e8-9f32-f2801f1b9fd","rf3a5a5c-e441-11e8-9f32-f2801f1b9hd1","ef3a5a5c-e441-11e8-9f32-f2801f2b9fd1"]
              }
  /{id}:
    uriParameters:
      id: string
    get:
      responses:
        200:
          body:
            application/json:
              type: offers
        404:
          body:
            application/json:
              example: {"Id not found"}
    put:
      body:
        application/json:
          type: offer
      responses:
        204:
          body:
            application/json:
              example: {"Update Complete"}
        404:
          body:
            application/json:
                example: {"no thing found"}

  /user/{id}:
    uriParameters:
      id: string
    get:
      responses:
        200:
          body:
            application/json:
              type: offers
        404:
          body:
            application/json:
              example: {"Id not found"}