#%RAML 1.0
title: Credit Cards
version: v1.0

/creditcards:
  /{userID}:
    get:
      description: retrieves the credit card(s) of the same userID
      responses:
        200:
          body:
            application/json:
              type: object
              properties:
                cardNumber:
                  required: true
                  pattern: '\d{4} \d{4} \d{4} \d{4}'
                  example: 1234 1234 1234 1234
                  description: Credit Card number
                  type: string
                balance:
                  required: true
                  minimum: 0
                  maximum: 1000000000
                  type: number
                status:
                  required: true
                  description: open, locked, expired, closed
                  enum: [active, locked, expired, closed]
                  type: string
                creditLine:
                  required: true
                  type: number
                expiration:
                  required: true
                  type: date-only
                userID:
                  required: true
                  type: string 
                reward:
                  type: number
                CVV:
                  required: true
                  type: number
                  minimum: 000
                  maximum: 999
                interestRate:
                  required: true
                  type: number
                  
              example:
                  cardNumber: 1234 5678 9101 2345
                  balance: 100.00
                  status: active
                  creditLine: 30
                  expiration: 2020-12-31
                  userID: 1ae23456789
                  reward: 100
                  CVV: 999
                  interestRate: 1.2
        400:
          body: 
            application/json:
              properties:
                message: string
              example: |
                {
                  "message": "Invalid userID"
                }
  /newCard:
    post:
      description: adds a new card to the userID account
      body:
        application/json:
          type: object
          properties:
            cardNumber:
              required: true
              pattern: '\d{4} \d{4} \d{4} \d{4}'
              example: 1234 1234 1234 1234
              description: Credit Card number
              type: string
            balance:
              required: true
              minimum: 0
              maximum: 1000000000
              type: number
            status:
              required: true
              description: open, closed, deactivated, expired
              enum: [active, closed, deactivated, expired]
              type: string
            creditLine:
              required: true
              type: number
            expiration:
              required: true
              type: date-only
            userID:
              required: true
              type: string 
            reward:
              type: number
            CVV:
              required: true
              type: number
              minimum: 000
              maximum: 999
            interestRate:
              required: true
              type: number
          example: |
            {
              "cardNumber": "1111 1111 1111 1111",
              "balance": 55,
              "status": "active",
              "creditLine": 30,
              "expiration": "2020-12-31",
              "userID": "eieio",
              "reward": 0,
              "CVV": 999,
              "interestRate": 1.2
            }
        
  /charge:
    put: 
      description: Add charge to credit card balance form vendor.
      responses: 
        200:
          body: 
            application/json:
              example: |
                {
                  "cardNumber": "1234 5678 9101 2345",
                  "balance": "150.00"
                }
        400:
          body:
            application/json:
              properties:
                message: string
              example: |
                {
                  "message": "Invalid request"
                }
  /payment:
    put: 
      description: Processes payment by user to credit card balance
      responses: 
        200:
          body: 
            application/json:
              example: |
                {
                  "cardNumber": "1234 5678 9101 2345",
                  "balance": "150.00"
                }
        400:
          body:
            application/json:
              properties:
                message: string
              example: |
                {
                  "message": "Invalid request"
                }
  /updatestatus:
    put: 
      description: update status of credit card
      responses: 
        200:
          body: 
            application/json:
              example: |
                {
                  "cardNumber": "1234 5678 9101 2345",
                  "status": "open"
                }
        400:
          body:
            application/json:
              properties:
                message: string
              example: |
                {
                  "message": "Invalid request"
                }

  /updatereward:
    put: 
      description: update reward of credit card
      responses: 
        200:
          body: 
            application/json:
              example: |
                {
                  "cardNumber": "1234 5678 9101 2345",
                  "reward": "150.00"
                }
        400:
          body:
            application/json:
              properties:
                message: string
              example: |
                {
                  "message": "Invalid request"
                }
   