DROP USER CUSTOMER CASCADE;

CREATE USER CUSTOMER
IDENTIFIED BY p4ssw0rd
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE temp

QUOTA 10M ON users;



GRANT connect, resource, 
CREATE SESSION, CREATE TABLE, CREATE VIEW to CUSTOMER;