#%RAML 1.0
title: NDF - Managers API
version: v1
baseUri: https://api.ndf-managers.com
/manager:
  /Aprove:
    /{id}:
      put:
        description: Approve the loan with loanid = {id}
        queryParameters:
          access_token:
            displayName: Access Token
            type: string
            description: Token giving permision to make call
            required: True
        body:
          application/json:
            example:  |
              {"message": "Loan approved"}
  /Deny:
    /{id}:
      put:
        description: Deny the loan with loanid = {id}
        queryParameters:
          access_token:
            displayName: Access Token
            type: string
            description: Token giving permision to make call
            required: True
        body:
          application/json:
            example:  |
              {"message": "Loan denied"}