#%RAML 1.0
title: NDF - Managers API
version: v1
baseUri: https://api.ndf-managers.com
/manager:
  /listPendingApp:
    get:
      description: List all pending applications
      responses:
        200:
          body:
            application/json:
  /getPendingAppById:
    /id:
      /{id}:
        post:
          queryParameters:
            id:
              displayName: id
              type: integer
              description: Loan id number
              example: 123456
              required: false
          description: Retrieve a specific application
          responses:
            200:
              body:
                application/json:
