DROP TABLE PENDING_LOANS;
DROP SEQUENCE PENDING_LOAN_ID_SEQUENCE;

CREATE TABLE PENDING_LOANS (
	PENDING_ID NUMBER(*,0) PRIMARY KEY,
	USER_ID VARCHAR2(50),
	PRINCIPLE NUMBER(*,2),
	TYPEOF VARCHAR2(25),
	INCOME NUMBER(*,0)
);

CREATE SEQUENCE PENDING_LOAN_ID_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER INSERT_PENDING_LOANS_ID 
BEFORE INSERT ON PENDING_LOANS
FOR EACH ROW
BEGIN
	SELECT PENDING_LOAN_ID_SEQUENCE.NEXTVAL INTO :NEW.PENDING_ID FROM DUAL;
END;
/